version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    environment:
      DEBUG: "True"
    volumes:
    - feeds:/feeds/
    - ./:/skim/
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: "True"
    volumes:
    - ./:/skim/
    entrypoint:
    - /usr/local/bin/pytest
    - --cov
    - --cov-report=term-missing
volumes:
  feeds:
