web:
  restart: on-failure
  build: .
  ports:
    - "3333:3333"
  volumes:
    - .:/skim/
    - example.opml:/tmp/seed.opml
  volumes_from:
    - storage
  environment:
    - PYTHONPATH=/skim/
    - ENV=development
  command: /skim/webserver

storage:
  restart: no
  image: busybox:latest
  volumes:
    - /storage/
  command: /bin/true
