version: "3.8"
services:
  manage:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    entrypoint: python -m manage
    volumes:
    - feeds:/feeds/
    - ./:/skim/
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    environment:
      PYTHONUNBUFFERED: 1
    command: watchfiles skim.server.run
    volumes:
    - feeds:/feeds/
    - ./:/skim/
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/skim/
    entrypoint:
    - pytest
volumes:
  feeds:
