[tool.pytest.ini_options]
minversion = "6.0"
addopts = """
    --black
    --cov=/skim/
    --cov-branch
    --cov-report=term-missing
    --cov-fail-under=100
"""

[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ['py39']

[tool.pylint.messages_control]
disable = [
    'missing-module-docstring',
    'missing-function-docstring',
]
