[tool.black]
skip-string-normalization = true
target-version = ['py310']

[tool.isort]
profile = 'black'

[tool.mypy]
namespace_packages = true

[[tool.mypy.overrides]]
module = ['asyncpg']
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ['humanize']
ignore_missing_imports = true

[tool.pylint.messages_control]
disable = [
    'fixme',
    'invalid-name',
    'missing-module-docstring',
    'missing-function-docstring',
    'redefined-outer-name',
    'unused-argument'
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = """
    --black
    --isort
    --pylint
    --mypy
    -n 4
    --cov=/skim/
    --cov-branch
    --cov-report=term-missing
    --cov-fail-under=100
    --no-cov-on-fail
"""

asyncio_mode = 'auto'
