#!/bin/bash
set -e

if [ ! -f /storage/subscriptions.opml ]; then
    if [ -f /tmp/seed.opml ]; then
        cp /tmp/seed.opml /storage/subscriptions.opml
    else
        echo 'No seed.opml and no subscriptions.opml'
    fi
fi

cd /skim
export PYTHONPATH=/skim/:$PYTHONPATH
if [ "$ENV" = 'development' ]; then
    while true; do
        sleep 1
        python3.4 -m skim.server 0.0.0.0:3333 || true
    done
else
    uwsgi --ini /skim/uwsgi.ini "$@"
fi
