#!/bin/bash
set -e

cd /skim
if [ "$ENV" = 'development' ]; then
    pip3 install -e .
    while true; do
        sleep 1
        python3.4 -m skim.server 0.0.0.0:3333 || true
    done
else
    uwsgi --ini /skim/uwsgi.ini
fi
